### ISSUE TITLE
ImportError: No module named 'addict'

### ISSUE THREAD

**Issue by c1a1o1** [SunnerLi/RecycleGAN#5]
Traceback (most recent call last):
  File "D:/work/work11/RecycleGAN-master/train.py", line 1, in <module>
    from lib.loader import get_loader, InfiniteLoader
  File "D:\work\work11\RecycleGAN-master\lib\loader\__init__.py", line 1, in <module>
    from lib.loader.video_loader import *
  File "D:\work\work11\RecycleGAN-master\lib\loader\video_loader.py", line 1, in <module>
    from addict import Dict
ImportError: No module named 'addict'

**Comment by SunnerLi** [comment]
Hi @c1a1o1 ,
Since the `addict` module can deal with dict operator elegantly,
we use this module in our implementation.
Just install this module and you can solve the problem!
```
pip3 install addict
```
If you have any other problem, welcome to re-open the issue :-)
